<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>Notes</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
</head>
<body>
<h1 id="notes"><strong>Notes</strong></h1>
<h2 id="determining-types"><strong>Determining Types</strong></h2>
<blockquote>
<p>Fun Fact: Operators like +, %, and = are called binary operators because they take two operands. The <strong>typeOf</strong> operator returns the type of data you call it on.</p>
</blockquote>
<pre><code>let s = &quot;This is a string&quot;;
console.log(typeof s); // &#39;string&#39;

let n = 6.28;
console.log(typeof n); // &#39;number&#39;

let sum = function (a, b) {
  return a + b;
};
console.log(typeof sum); // &#39;function&#39;</code></pre>
<ul>
<li>Due to a very old bug in JS, typeOf used on an array will return it as an object.</li>
<li><p>So we can use *<em>Array.isArray</em> to test to see if a value is an array.</p>
<p>let a = [1, 2, 3]; Array.isArray(a); // true</p>
<p>let n = 6.28; Array.isArray(n); // false</p>
<p>let f = function () {}; Array.isArray(f); // false</p></li>
<li><p>Practical use in “real code” is if you believe that whoever is using your program will not respect your parameters.</p></li>
</ul>
<hr />
<h2 id="null-unidentified-types"><strong>Null &amp; Unidentified Types</strong></h2>
<p>The <strong>null type</strong> has one and only value: null.</p>
<p><strong>The meaning of Null</strong></p>
<ul>
<li>The meaning of Null is almost philosophical.</li>
<li>The code you write determines the meaning of Null.
<ul>
<li>Null could mean <em>the absence of a value or no value</em>.</li>
<li>Null could mean <em>an unknown value</em>.</li>
</ul></li>
<li>We can check for null by using the strict equality operator.</li>
</ul>
<p><strong>The absence of a value</strong></p>
<pre><code>function reverseTheSentence(sentence) {
  if (typeof sentence !== &quot;string&quot;) {
    return null;
  }
  let parts = sentence.split(&quot; &quot;);
  parts.reverse();
  return parts.join(&quot; &quot;);
}</code></pre>
<ul>
<li>In the above example we are passing in a string, splitting it into an array on a space, using the array method reverse to reverse the elements of the array, and joining the array back into a string on a space.</li>
<li>Our conditional at the top assures we will return null if someone disrepsectfully passes in a data type that isn’t a string!</li>
</ul>
<h2 id="undefined"><strong>Undefined</strong></h2>
<p><strong>Undefined</strong> is the only value of the undefined data type.</p>
<ul>
<li>Uninitialized variables have a value of undefined.</li>
<li>In JS, <strong>Null</strong> is an object, and <strong>Undefined</strong> is a data type.</li>
<li>Null can also be an assignment value.</li>
<li>All functions will output undefined by default if there is no return statement.</li>
<li>We can check for undefined by using the strict equality operator.</li>
</ul>
<hr />
<h2 id="structured-exception-handling-seh"><strong>Structured Exception Handling (SEH)</strong></h2>
<p>Tools to help handle certain exceptional code situations, such as hardware faults, gracefully.</p>
<ul>
<li><p>There are only three ways of handling exceptions right now in pgroamming:</p>
<ul>
<li><strong>Error or Error Code Reporting</strong> (C &amp; Go)</li>
<li><strong>Continuable Exceptions</strong> (Common Lisp)</li>
<li><strong>Stack Unwinding</strong> (Found in almost every modern programming language including <strong><em>Javascript and Python</em></strong>)</li>
</ul></li>
<li><p>How it works is that when an error occurs, your Javascript interpreter will look for a handler to manage the error.</p></li>
</ul>
<p><strong>Try and Catch</strong></p>
<ul>
<li><strong>Code Block</strong> : If there are curly braces around some lines of code it is considered a code block.
<ul>
<li>Examples would be If, for, and function blocks!</li>
</ul></li>
<li><strong>Try</strong> blocks tells JS it needs to watch for some errors in the code it’s blocked off.</li>
<li><strong>Catch</strong> blocks tell JS what to do in the event there <em>is</em> an error.</li>
<li><p><strong>MAKE SURE</strong> you fill out the catch block!</p>
<p>function sumArray(array) { let sum = 0;</p>
<p>try { for (let i = 0; i &lt; array.length; i += 1) { sum += array[i]; } } catch (e) { console.log(e); return null; } finally { console.log(“you will always see this.”); }</p>
<p>return sum; }</p></li>
<li>The <strong><em>catch block</em></strong> runs when an error occurs in the <strong><em>try block</em></strong>.</li>
<li>The ‘e’ after catch represents the error thrown in the catch. (can also be named ‘err’ or ‘error’)</li>
<li><p>The <strong><em>finally block</em></strong> is the last block on the try-catch block, it always runs whether or not an error occurs.</p>
<p>TypeError: Cannot read property ‘length’ of null at sumArray (/tmp/file.js:5:31) at Object.<anonymous> (/tmp/file.js:16:1) at Module._compile (internal/modules/cjs/loader.js:1158:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) at Module.load (internal/modules/cjs/loader.js:1002:32) at Function.Module._load (internal/modules/cjs/loader.js:901:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) at internal/main/run_main_module.js:18:47</p></li>
<li>The line after <strong>TypeError</strong> indicates the exception that has occured.</li>
<li>The next 10 lines are known as a <strong>Stack Trace</strong></li>
<li><p>The first line in the Stack Trace indicate <em>where</em> the error occured.</p></li>
</ul>
<p><strong>How can I make my own Errors?</strong></p>
<p>You can create your own “errors” by creating an error object paired with an error message.</p>
<pre><code>throw Error(&quot;this happened because I wanted it to&quot;);
throw new Error(&quot;this happened because I wanted it to&quot;);</code></pre>
<p><strong>How do I best use this?</strong></p>
<ul>
<li>Every try-catch block slows down your code, so you want to write as few of them as possible.</li>
<li>You should practice <strong>defensive coding</strong> which checks for bad values before errors are thrown.</li>
<li><p>To go back to the sum array example, instead you should try-catch block the parameter, since this is the area you’d run in to the most trouble.</p>
<p>function sumArray(array) { if (array === null) { return null; }</p>
<p>let sum = 0; for (let i = 0; i &lt; array.length; i += 1) { sum += array[i]; } return sum; }</p></li>
</ul>
<blockquote>
<p>Fun Fact: If you divide an integer with zero in JS you will output infinity or neg. infinity.</p>
</blockquote>
<pre><code>let guestList = [&quot;Leonardo&quot;, &quot;Michaelangelo&quot;, &quot;Donatello&quot;, &quot;Raphael&quot;];
let queue = [&quot;Bobby&quot;, &quot;Donatello&quot;, &quot;Raphael&quot;, &quot;Tom&quot;];

for (let i = 0; i &lt; queue.length; i++) {
  let person = queue[i];
  try {
    if (!guestList.includes(person)) {
      throw new Error(person + &quot;wasn&#39;t invited&quot;);
    } else {
      console.log(&quot;Welcome to the party,&quot; + person);
    }
  } catch (e) {
    console.log(e.message);
  } finally {
    console.log(&quot;this always runs&quot;);
  }
}</code></pre>
<ul>
<li>User generated error in our conditional initiated by ‘throw new Error(//message)’</li>
<li>In our catch block, we print out our custom error message by typing in ‘e.message’.</li>
</ul>
<hr />
</body>
</html>
